export const ADD_SALE_ENTRY = "ADD_SALE_ENTRY";
export const FETCH_SALE_DATA = "FETCH_SALE_DATA";
export const EDIT_SALE_ENTRY = "EDIT_SALE_ENTRY";
export const FETCH_STOCKS = "FETCH_STOCKS";
export const CHANGE_FORM_DATA = "CHANGE_FORM_DATA";
export const CLEAR_FORM_DATA = "CLEAR_FORM_DATA";
